In [1]:
import pandas as pd

In [2]:
import seaborn as sns

In [3]:
tips = sns.load_dataset('tips')

In [4]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
from sklearn import linear_model

In [6]:
lr = linear_model.LinearRegression()

In [7]:
lr.fit(X=tips[['total_bill', 'size']], y=tips['tip'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
lr.coef_

array([0.09271334, 0.19259779])

In [9]:
# stats models gives you a summary model but scikit does not
lr.intercept_

0.6689447408125022

In [10]:
lr = linear_model.LinearRegression()
lr.fit(X=tips[['total_bill', 'day']], y=tips['tip'])

ValueError: could not convert string to float: 'Sun'

In [11]:
pd.get_dummies(tips) # converts strings into kind of a numerical code

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,0,1,0,1,0,0,0,1,0,1
1,10.34,1.66,3,1,0,0,1,0,0,0,1,0,1
2,21.01,3.50,3,1,0,0,1,0,0,0,1,0,1
3,23.68,3.31,2,1,0,0,1,0,0,0,1,0,1
4,24.59,3.61,4,0,1,0,1,0,0,0,1,0,1
5,25.29,4.71,4,1,0,0,1,0,0,0,1,0,1
6,8.77,2.00,2,1,0,0,1,0,0,0,1,0,1
7,26.88,3.12,4,1,0,0,1,0,0,0,1,0,1
8,15.04,1.96,2,1,0,0,1,0,0,0,1,0,1
9,14.78,3.23,2,1,0,0,1,0,0,0,1,0,1
10,10.27,1.71,2,1,0,0,1,0,0,0,1,0,1
11,35.26,5.00,4,0,1,0,1,0,0,0,1,0,1
12,15.42,1.57,2,1,0,0,1,0,0,0,1,0,1
13,18.43,3.00,4,1,0,0,1,0,0,0,1,0,1
14,14.83,3.02,2,0,1,0,1,0,0,0,1,0,1
15,21.58,3.92,2,1,0,0,1,0,0,0,1,0,1
16,10.33,1.67,3,0,1,0,1,0,0,0,1,0,1
17,16.29,3.71,3,1,0,0,1,0,0,0,1,0,1
18,16.97,3.50,3,0,1,0,1,0,0,0,1,0,1
19,20.65,3.35,3,1,0,0,1,0,0,1,0,0,1
20,17.92,4.08,2,1,0,0,1,0,0,1,0,0,1
21,20.29,2.75,2,0,1,0,1,0,0,1,0,0,1
22,15.77,2.23,2,0,1,0,1,0,0,1,0,0,1
23,39.42,7.58,4,1,0,0,1,0,0,1,0,0,1
24,19.82,3.18,2,1,0,0,1,0,0,1,0,0,1
25,17.81,2.34,4,1,0,0,1,0,0,1,0,0,1
26,13.37,2.00,2,1,0,0,1,0,0,1,0,0,1
27,12.69,2.00,2,1,0,0,1,0,0,1,0,0,1
28,21.70,4.30,2,1,0,0,1,0,0,1,0,0,1
29,19.65,3.00,2,0,1,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,28.17,6.50,3,0,1,1,0,0,0,1,0,0,1
215,12.90,1.10,2,0,1,1,0,0,0,1,0,0,1
216,28.15,3.00,5,1,0,1,0,0,0,1,0,0,1
217,11.59,1.50,2,1,0,1,0,0,0,1,0,0,1
218,7.74,1.44,2,1,0,1,0,0,0,1,0,0,1
219,30.14,3.09,4,0,1,1,0,0,0,1,0,0,1
220,12.16,2.20,2,1,0,1,0,0,1,0,0,1,0
221,13.42,3.48,2,0,1,1,0,0,1,0,0,1,0
222,8.58,1.92,1,1,0,1,0,0,1,0,0,1,0
223,15.98,3.00,3,0,1,0,1,0,1,0,0,1,0
224,13.42,1.58,2,1,0,1,0,0,1,0,0,1,0
225,16.27,2.50,2,0,1,1,0,0,1,0,0,1,0
226,10.09,2.00,2,0,1,1,0,0,1,0,0,1,0
227,20.45,3.00,4,1,0,0,1,0,0,1,0,0,1
228,13.28,2.72,2,1,0,0,1,0,0,1,0,0,1
229,22.12,2.88,2,0,1,1,0,0,0,1,0,0,1
230,24.01,2.00,4,1,0,1,0,0,0,1,0,0,1
231,15.69,3.00,3,1,0,1,0,0,0,1,0,0,1
232,11.61,3.39,2,1,0,0,1,0,0,1,0,0,1
233,10.77,1.47,2,1,0,0,1,0,0,1,0,0,1
234,15.53,3.00,2,1,0,1,0,0,0,1,0,0,1
235,10.07,1.25,2,1,0,0,1,0,0,1,0,0,1
236,12.60,1.00,2,1,0,1,0,0,0,1,0,0,1
237,32.83,1.17,2,1,0,1,0,0,0,1,0,0,1
238,35.83,4.67,3,0,1,0,1,0,0,1,0,0,1
239,29.03,5.92,3,1,0,0,1,0,0,1,0,0,1
240,27.18,2.00,2,0,1,1,0,0,0,1,0,0,1
241,22.67,2.00,2,1,0,1,0,0,0,1,0,0,1
242,17.82,1.75,2,1,0,0,1,0,0,1,0,0,1
243,18.78,3.00,2,0,1,0,1,1,0,0,0,0,1

In [13]:
tips_dummy = pd.get_dummies(tips, drop_first=True) # converts strings into kind of a numerical code

In [15]:
tips_dummy

,total_bill,tip,size,sex_Female,smoker_No,day_Fri,day_Sat,day_Sun,time_Dinner
0,16.99,1.01,2,1,1,0,0,1,1
1,10.34,1.66,3,0,1,0,0,1,1
2,21.01,3.50,3,0,1,0,0,1,1
3,23.68,3.31,2,0,1,0,0,1,1
4,24.59,3.61,4,1,1,0,0,1,1
5,25.29,4.71,4,0,1,0,0,1,1
6,8.77,2.00,2,0,1,0,0,1,1
7,26.88,3.12,4,0,1,0,0,1,1
8,15.04,1.96,2,0,1,0,0,1,1
9,14.78,3.23,2,0,1,0,0,1,1
10,10.27,1.71,2,0,1,0,0,1,1
11,35.26,5.00,4,1,1,0,0,1,1
12,15.42,1.57,2,0,1,0,0,1,1
13,18.43,3.00,4,0,1,0,0,1,1
14,14.83,3.02,2,1,1,0,0,1,1
15,21.58,3.92,2,0,1,0,0,1,1
16,10.33,1.67,3,1,1,0,0,1,1
17,16.29,3.71,3,0,1,0,0,1,1
18,16.97,3.50,3,1,1,0,0,1,1
19,20.65,3.35,3,0,1,0,1,0,1
20,17.92,4.08,2,0,1,0,1,0,1
21,20.29,2.75,2,1,1,0,1,0,1
22,15.77,2.23,2,1,1,0,1,0,1
23,39.42,7.58,4,0,1,0,1,0,1
24,19.82,3.18,2,0,1,0,1,0,1
25,17.81,2.34,4,0,1,0,1,0,1
26,13.37,2.00,2,0,1,0,1,0,1
27,12.69,2.00,2,0,1,0,1,0,1
28,21.70,4.30,2,0,1,0,1,0,1
29,19.65,3.00,2,1,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...
214,28.17,6.50,3,1,0,0,1,0,1
215,12.90,1.10,2,1,0,0,1,0,1
216,28.15,3.00,5,0,0,0,1,0,1
217,11.59,1.50,2,0,0,0,1,0,1
218,7.74,1.44,2,0,0,0,1,0,1
219,30.14,3.09,4,1,0,0,1,0,1
220,12.16,2.20,2,0,0,1,0,0,0
221,13.42,3.48,2,1,0,1,0,0,0
222,8.58,1.92,1,0,0,1,0,0,0
223,15.98,3.00,3,1,1,1,0,0,0
224,13.42,1.58,2,0,0,1,0,0,0
225,16.27,2.50,2,1,0,1,0,0,0
226,10.09,2.00,2,1,0,1,0,0,0
227,20.45,3.00,4,0,1,0,1,0,1
228,13.28,2.72,2,0,1,0,1,0,1
229,22.12,2.88,2,1,0,0,1,0,1
230,24.01,2.00,4,0,0,0,1,0,1
231,15.69,3.00,3,0,0,0,1,0,1
232,11.61,3.39,2,0,1,0,1,0,1
233,10.77,1.47,2,0,1,0,1,0,1
234,15.53,3.00,2,0,0,0,1,0,1
235,10.07,1.25,2,0,1,0,1,0,1
236,12.60,1.00,2,0,0,0,1,0,1
237,32.83,1.17,2,0,0,0,1,0,1
238,35.83,4.67,3,1,1,0,1,0,1
239,29.03,5.92,3,0,1,0,1,0,1
240,27.18,2.00,2,1,0,0,1,0,1
241,22.67,2.00,2,0,0,0,1,0,1
242,17.82,1.75,2,0,1,0,1,0,1
243,18.78,3.00,2,1,1,0,0,0,1

In [16]:
tips_dummy.columns

Index(['total_bill', 'tip', 'size', 'sex_Female', 'smoker_No', 'day_Fri',
       'day_Sat', 'day_Sun', 'time_Dinner'],
      dtype='object')

In [19]:
lr = linear_model.LinearRegression()
lr.fit(X=tips_dummy[['total_bill', 'size', 'sex_Female', 'smoker_No', 'day_Fri',
       'day_Sat', 'day_Sun', 'time_Dinner']], y=tips_dummy['tip'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
lr.coef_ # if the sex was female, you have increase of 3 cents in tip. If the party shows up on Friday, 16 cents increased compared to Thursday

array([ 0.09448701,  0.175992  ,  0.03244094,  0.08640832,  0.1622592 ,
        0.04080082,  0.13677854, -0.0681286 ])

In [ ]:
# check scikit assumptions